UI_TRANSLATIONS = {
    "English": {
        "title": "🇿🇦 Project Ithuba",
        "subtitle": "Your Voice is Your CV",
        "step1": "🎙️ Step 1: Provide your story",
        "step2": "📝 Step 2: Review or Edit",
        "review_label": "Review your story:",
        "placeholder_story": "Describe your daily work/business...",
        "step3": "👤 Step 3: Personalize",
        "name_label": "Enter your Full Name (for the PDF header):",
        "step4": "🎯 Step 4: Target Job (Optional)",
        "jd_label": "Paste Job Description:",
        "placeholder_jd": "Paste the requirements or job ad here...",
        "gen_btn": "Generate ✨",
        "sidebar_head": "⚙️ Settings",
        "lang_label": "Language Preference:",
        "about_head": "About",
        "mission": "Bridging the gap between informal experience and formal recognition."
    },
    "isiZulu": {
        "title": "🇿🇦 Umsebenzi Ithuba",
        "subtitle": "Izwi lakho yi-CV yakho",
        "step1": "🎙️ Isinyathelo 1: Landa indaba yakho",
        "step2": "📝 Isinyathelo 2: Buyekeza noma Hlela",
        "review_label": "Buyekeza indaba yakho:",
        "placeholder_story": "Chaza umsebenzi wakho wansuku zonke...",
        "step3": "👤 Isinyathelo 3: Yenza kube ngokwakho",
        "name_label": "Faka igama lakho eliphelele (le-PDF):",
        "step4": "🎯 Isinyathelo 4: Umsebenzi ohlosiwe (Optional)",
        "jd_label": "Namathisela incazelo yomsebenzi:",
        "placeholder_jd": "Namathisela izidingo zomsebenzi lapha...",
        "gen_btn": "Yenza i-CV ✨",
        "sidebar_head": "⚙️ Izilungiselelo",
        "lang_label": "Ulimi olukhethayo:",
        "about_head": "Mayelana",
        "mission": "Ukuvala igebe phakathi kokuhlangenwe nakho okungahlelekile nokuqashelwa okusemthethweni."
    },
    "isiXhosa": {
        "title": "🇿🇦 Iprojekthi Ithuba",
        "subtitle": "Ilizwi lakho yi-CV yakho",
        "step1": "🎙️ Inyathelo 1: Balisa ibali lakho",
        "step2": "📝 Inyathelo 2: Phinda ujonge okanye Uhlele",
        "review_label": "Phinda ujonge ibali lakho:",
        "placeholder_story": "Chaza umsebenzi wakho wemihla ngemihla...",
        "step3": "👤 Inyathelo 3: Yenza ngokwakho",
        "name_label": "Faka iGama lakho elipheleleyo (le-PDF):",
        "step4": "🎯 Inyathelo 4: Umsebenzi ekujoliswe kuwo (Optional)",
        "jd_label": "Camathisela inkcazo yomsebenzi:",
        "placeholder_jd": "Camathisela iimfuno zomsebenzi apha...",
        "gen_btn": "Yenza i-CV ✨",
        "sidebar_head": "⚙️ Izicwangciso",
        "lang_label": "Ulwimi olukhethwayo:",
        "about_head": "Malunga",
        "mission": "Ukuvala umsantsa phakathi kwamava angaphaya nokuqatshelwa okusesikweni."
    },
    "Afrikaans": {
        "title": "🇿🇦 Projek Ithuba",
        "subtitle": "Jou stem is jou CV",
        "step1": "🎙️ Stap 1: Vertel jou storie",
        "step2": "📝 Stap 2: Hersien of Wysig",
        "review_label": "Hersien jou storie:",
        "placeholder_story": "Beskryf jou daaglikse werk...",
        "step3": "👤 Stap 3: Verpersoonlik",
        "name_label": "Voer jou volle naam in (vir die PDF-opskrif):",
        "step4": "🎯 Stap 4: Doelwit Werk (Opsioneel)",
        "jd_label": "Plak posbeskrywing:",
        "placeholder_jd": "Plak die posvereistes hier...",
        "gen_btn": "Genereer ✨",
        "sidebar_head": "⚙️ Instellings",
        "lang_label": "Taalvoorkeur:",
        "about_head": "Oor",
        "mission": "Oorbrug die gaping tussen informele ervaring en formele erkenning."
    },
    "Sepedi": {
        "title": "🇿🇦 Protšeke ya Ithuba",
        "subtitle": "Lentšu la gago ke CV ya gago",
        "step1": "🎙️ Kgato 1: Anega kanegelo ya gago",
        "step2": "📝 Kgato 2: Bušeletša goba o Fetole",
        "review_label": "Bušeletša kanegelo ya gago:",
        "placeholder_story": "Hlaloša mošomo wa gago wa tšatši le tšatši...",
        "step3": "👤 Kgato 3: Ikgethele",
        "name_label": "Ngwala leina la gago ka botlalo (la PDF):",
        "step4": "🎯 Kgato 4: Mošomo wo o u nyakago (Optional)",
        "jd_label": "Kgokaganya thlalošo ya mošomo:",
        "placeholder_jd": "Kgokaganya dinyakwa tša mošomo mo...",
        "gen_btn": "Tšweletša ✨",
        "sidebar_head": "⚙️ Dipeakanyo",
        "lang_label": "Leleme le o le kgethago:",
        "about_head": "Ka ga",
        "mission": "Go kopanya sekgoba magareng ga boitemogelo bja go se be molaong le temogo ya semolaong."
    },
    "Setswana": {
        "title": "🇿🇦 Porojeke ya Ithuba",
        "subtitle": "Lentswe la gago ke CV ya gago",
        "step1": "🎙️ Kgato 1: Bolela kgang ya gago",
        "step2": "📝 Kgato 2: Sekaseka kgotsa o Fetole",
        "review_label": "Sekaseka kgang ya gago:",
        "placeholder_story": "Tlhalosa tiro ya gago ya malatsi otlhe...",
        "step3": "👤 Kgato 3: Itekanyetsetse",
        "name_label": "Kwala leina la gago ka botlalo (la PDF):",
        "step4": "🎯 Kgato 4: Tiro e o e batlang (Optional)",
        "jd_label": "Mamaretsa thlhaloso ya tiro:",
        "placeholder_jd": "Mamaretsa ditlhokego tsa tiro fano...",
        "gen_btn": "Tlhamisa ✨",
        "sidebar_head": "⚙️ Dipeakanyo",
        "lang_label": "Puo e o e tlhophang:",
        "about_head": "Ka ga",
        "mission": "Go bridging sekgala gareng ga maitemogelo a a sa rulaganang le kamogelo ya semmuso."
    },
    "Sesotho": {
        "title": "🇿🇦 Morero wa Ithuba",
        "subtitle": "Lentswe la hao ke CV ya hao",
        "step1": "🎙️ Mohato 1: Pheta pale ya hao",
        "step2": "📝 Mohato 2: Hlahloba kapa o Fetole",
        "review_label": "Hlahloba pale ya hao:",
        "placeholder_story": "Hlalosa mosebetsi wa hao wa letsatsi le letsatsi...",
        "step3": "👤 Mohato 3: Ikgethele",
        "name_label": "Kenya lebitso la hao ka botlalo (la PDF):",
        "step4": "🎯 Mohato 4: Mosebetsi o o batlang (Optional)",
        "jd_label": "Mamaretsa thlaloso ea mosebetsi:",
        "placeholder_jd": "Mamaretsa ditlhoko tsa mosebetsi mona...",
        "gen_btn": "Hlahisa ✨",
        "sidebar_head": "⚙️ Dipeakanyo",
        "lang_label": "Puo eo u e ratang:",
        "about_head": "Mabapi le",
        "mission": "Ho koala lekhalo lipakeng tsa boiphihlelo bo sa reroang le kamohelo ea semmuso."
    },
    "Xitsonga": {
        "title": "🇿🇦 Phurojeke ya Ithuba",
        "subtitle": "Rito ra wena i CV ya wena",
        "step1": "🎙️ Goza 1: Hlamusela ntsheketo wa wena",
        "step2": "📝 Goza 2: Kambisisa kumbe u lulamisa",
        "review_label": "Kambisisa ntsheketo wa wena:",
        "placeholder_story": "Hlamusela ntirho wa wena wa siku ni siku...",
        "step3": "👤 Goza 3: Tihlawulele",
        "name_label": "Tsala vito ra wena hi ku hetiseka (ra PDF):",
        "step4": "🎯 Goza 4: Ntirho lowu u wu lavaka (Optional)",
        "jd_label": "Nametela nhlamuselo ya ntirho:",
        "placeholder_jd": "Nametela swilaveko swa ntirho laha...",
        "gen_btn": "Endla ✨",
        "sidebar_head": "⚙️ Swiyimiso",
        "lang_label": "Ririmi leri u ri lavaka:",
        "about_head": "Swithu",
        "mission": "Ku pfala nkhaviso exikarhi ka ntokoto lowu nga riki enawini ni ku amukeriwa loku nga enawini."
    },
    "siSwati": {
        "title": "🇿🇦 Umklamo we-Ithuba",
        "subtitle": "Livi lakho yi-CV yakho",
        "step1": "🎙️ Linyatselo 1: Landza indzaba yakho",
        "step2": "📝 Linyatselo 2: Buyeketa noma Uhlele",
        "review_label": "Buyeketa indzaba yakho:",
        "placeholder_story": "Chaza umsebenti wakho wamalanga onkhe...",
        "step3": "👤 Linyatselo 3: Kwenta kube kwakho",
        "name_label": "Bhala ligama lakho leliphelele (le-PDF):",
        "step4": "🎯 Linyatselo 4: Umsebenti lohlosiwe (Optional)",
        "jd_label": "Namatsela inchazelo yemsebenti:",
        "placeholder_jd": "Namatsela timfuneko temsebenti lapha...",
        "gen_btn": "Yenta ✨",
        "sidebar_head": "⚙️ Tinhlelo",
        "lang_label": "Lulwimi lolukhetsako:",
        "about_head": "Mayelana",
        "mission": "Kuvala sikhala emkhatsini welwati lolungakahleleki nekwatiwa lokusemtsetfweni."
    },
    "Tshivenda": {
        "title": "🇿🇦 Phurojekiti ya Ithuba",
        "subtitle": "Ipfi lau ndi CV yau",
        "step1": "🎙️ vhukando 1: vhambadza tshitori tshau",
        "step2": "📝 vhukando 2: sedzulusa kana u khwinisa",
        "review_label": "Sedzulusa tshitori tshau:",
        "placeholder_story": "Talutshedza mushumo wau wa duvha na duvha...",
        "step3": "👤 vhukando 3: dzhia sa zwau",
        "name_label": "Ñwalani dzina lau lo fhelelaho (la PDF):",
        "step4": "🎯 vhukando 4: Mushumo u re ntha (Optional)",
        "jd_label": "Nambatedza thalutshedzo ya mushumo:",
        "placeholder_jd": "Nambatedza thodea dza mushumo hafha...",
        "gen_btn": "Bveledza ✨",
        "sidebar_head": "⚙️ Zwilinganyo",
        "lang_label": "Luambo lune wa khetha:",
        "about_head": "Nga ha",
        "mission": "U pfala gake vhukati ha tshenzhelo i songo dzudzanyiwaho na u dzhielwa ntha ha tshiofisi."
    },
    "isiNdebele": {
        "title": "🇿🇦 Iprojekthi ye-Ithuba",
        "subtitle": "Ilizwi lakho yi-CV yakho",
        "step1": "🎙️ Igadango 1: Landula indaba yakho",
        "step2": "📝 Igadango 2: Buyekeza namkha tjhugulula",
        "review_label": "Buyekeza indaba yakho:",
        "placeholder_story": "Hlaloza umsebenzi wakho wamalanga woke...",
        "step3": "👤 Igadango 3: Zenzele",
        "name_label": "Tlowatlowa ibizo lakho elizeleko (le-PDF):",
        "step4": "🎯 Igadango 4: Umsebenzi ohlosiweko (Optional)",
        "jd_label": "Namathisela ihlaloso yomsebenzi:",
        "placeholder_jd": "Namathisela iimfuneko zomsebenzi lapha...",
        "gen_btn": "Yenza ✨",
        "sidebar_head": "⚙️ Izilungiselelo",
        "lang_label": "Ilimi elikhethwako:",
        "about_head": "Mayelana",
        "mission": "Ukuvala itjhinga hlangana nelwazi elingasomthetho nokutjhejwa kwesimthetho."
    }
}